### ISSUE TITLE
Alert to translators

### ISSUE THREAD

**Issue by seankross** [swirldev/translations#13]
@swirldev/translators:

I plan to submit the new version of swirl to CRAN within the next seven days. If there are any changes you would like to make, please make then as soon as possible.

If you would like to see your contributions in action, check out the latest development version of swirl:

``` r
# Install devtools if you need to
# install.packages("devtools")

library(devtools)
install_github("swirldev/swirl", ref = "dev")

library(swirl)
select_language()
swirl()
```

Sean

**Comment by nFrechen** [comment]
I am sorry to react this late. But I found some mistakes in the translation that will probably affect all languages:

If I test it there are some phrases that are still in English and that I don't find in the translation repository. Like:

```
Please don't use any quotes or other punctuation in your name
```

or 

```
Let's cover a few quick housekeeping items 
```

or

```
Please don't use any quotes or other punctuation in your name
```

Then this one:

```
You can exit swirl and return to the R prompt
```

is in my translation, but since it appears double (line 328 and 329) in the english.yaml file I think the translation does not show when I test it. Same for:

```
That's your cue to press Enter to continue
```

(line 310 and 311) and

```
Leaving swirl now. Type swirl() to resume
```

(line 470 and 471)

But anyway it is nice to be able to test this! Good work!

**Comment by ismaeIfm** [comment]
So it's been released or only testing? How can I test it?

**Comment by ismaeIfm** [comment]
Do we have to add those lines?

**Comment by nFrechen** [comment]
I think so. And remove the double entry lines. And maybe there are more missing.

**Comment by seankross** [comment]
Hi @swirldev/translators:

The following phrases need to be added for the following languages:

```
chinese_simplified : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
french : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
german : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
korean : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
spanish : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
turkish : 'Please specify a value for either course_name or swc_path but not both.' : install_course.R
chinese_simplified : 'It looks like your internet connection is not working.' : install_course.R
french : 'It looks like your internet connection is not working.' : install_course.R
german : 'It looks like your internet connection is not working.' : install_course.R
korean : 'It looks like your internet connection is not working.' : install_course.R
spanish : 'It looks like your internet connection is not working.' : install_course.R
turkish : 'It looks like your internet connection is not working.' : install_course.R
chinese_simplified : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
french : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
german : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
korean : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
spanish : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
turkish : 'Go to http://swirlstats.com/scn/ and download the .swc file that corresponds to the course you wish to install.' : install_course.R
chinese_simplified : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
french : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
german : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
korean : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
spanish : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
turkish : 'After downloading the .swc run install_course() and choose the file you downloaded.' : install_course.R
chinese_simplified : 'Could not connect to course file.' : install_course.R
french : 'Could not connect to course file.' : install_course.R
german : 'Could not connect to course file.' : install_course.R
korean : 'Could not connect to course file.' : install_course.R
spanish : 'Could not connect to course file.' : install_course.R
turkish : 'Could not connect to course file.' : install_course.R
chinese_simplified : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
french : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
german : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
korean : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
spanish : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
turkish : 'Are you sure you want to uninstall all swirl courses?' : install_course.R
chinese_simplified : 'This will delete all of the contents of your swirl course directory.' : install_course.R
french : 'This will delete all of the contents of your swirl course directory.' : install_course.R
german : 'This will delete all of the contents of your swirl course directory.' : install_course.R
korean : 'This will delete all of the contents of your swirl course directory.' : install_course.R
spanish : 'This will delete all of the contents of your swirl course directory.' : install_course.R
turkish : 'This will delete all of the contents of your swirl course directory.' : install_course.R
chinese_simplified : 'right now. Are you sure you have an internet connection?' : menu.R
french : 'right now. Are you sure you have an internet connection?' : menu.R
german : 'right now. Are you sure you have an internet connection?' : menu.R
korean : 'right now. Are you sure you have an internet connection?' : menu.R
spanish : 'right now. Are you sure you have an internet connection?' : menu.R
turkish : 'right now. Are you sure you have an internet connection?' : menu.R
chinese_simplified : 'If so, would you like to try again or visit' : menu.R
french : 'If so, would you like to try again or visit' : menu.R
german : 'If so, would you like to try again or visit' : menu.R
korean : 'If so, would you like to try again or visit' : menu.R
spanish : 'If so, would you like to try again or visit' : menu.R
turkish : 'If so, would you like to try again or visit' : menu.R
chinese_simplified : 'the course repository for instructions on how to' : menu.R
french : 'the course repository for instructions on how to' : menu.R
german : 'the course repository for instructions on how to' : menu.R
korean : 'the course repository for instructions on how to' : menu.R
spanish : 'the course repository for instructions on how to' : menu.R
turkish : 'the course repository for instructions on how to' : menu.R
chinese_simplified : 'install a course manually? Type 0 to exit.' : menu.R
french : 'install a course manually? Type 0 to exit.' : menu.R
german : 'install a course manually? Type 0 to exit.' : menu.R
korean : 'install a course manually? Type 0 to exit.' : menu.R
spanish : 'install a course manually? Type 0 to exit.' : menu.R
turkish : 'install a course manually? Type 0 to exit.' : menu.R
chinese_simplified : 'Please don't use any quotes or other punctuation in your name.' : menu.R
french : 'Please don't use any quotes or other punctuation in your name.' : menu.R
german : 'Please don't use any quotes or other punctuation in your name.' : menu.R
korean : 'Please don't use any quotes or other punctuation in your name.' : menu.R
turkish : 'Please don't use any quotes or other punctuation in your name.' : menu.R
chinese_simplified : '\n...  <-- That's your cue to press Enter to continue' : menu.R
english : '\n...  <-- That's your cue to press Enter to continue' : menu.R
french : '\n...  <-- That's your cue to press Enter to continue' : menu.R
german : '\n...  <-- That's your cue to press Enter to continue' : menu.R
korean : '\n...  <-- That's your cue to press Enter to continue' : menu.R
spanish : '\n...  <-- That's your cue to press Enter to continue' : menu.R
turkish : '\n...  <-- That's your cue to press Enter to continue' : menu.R
chinese_simplified : '\nSelect 1, 2, or 3 and press Enter' : menu.R
english : '\nSelect 1, 2, or 3 and press Enter' : menu.R
french : '\nSelect 1, 2, or 3 and press Enter' : menu.R
german : '\nSelect 1, 2, or 3 and press Enter' : menu.R
korean : '\nSelect 1, 2, or 3 and press Enter' : menu.R
spanish : '\nSelect 1, 2, or 3 and press Enter' : menu.R
turkish : '\nSelect 1, 2, or 3 and press Enter' : menu.R
chinese_simplified : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
french : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
german : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
korean : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
spanish : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
turkish : 'You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting you know you've done so.' : menu.R
chinese_simplified : 'All that hard work is paying off!' : phrases.R
french : 'All that hard work is paying off!' : phrases.R
german : 'All that hard work is paying off!' : phrases.R
korean : 'All that hard work is paying off!' : phrases.R
turkish : 'All that hard work is paying off!' : phrases.R
chinese_simplified : 'Keep working like that and you'll get there!' : phrases.R
french : 'Keep working like that and you'll get there!' : phrases.R
german : 'Keep working like that and you'll get there!' : phrases.R
korean : 'Keep working like that and you'll get there!' : phrases.R
turkish : 'Keep working like that and you'll get there!' : phrases.R
chinese_simplified : 'Perseverance, that's the answer.' : phrases.R
french : 'Perseverance, that's the answer.' : phrases.R
german : 'Perseverance, that's the answer.' : phrases.R
korean : 'Perseverance, that's the answer.' : phrases.R
turkish : 'Perseverance, that's the answer.' : phrases.R
chinese_simplified : 'Your dedication is inspiring!' : phrases.R
french : 'Your dedication is inspiring!' : phrases.R
german : 'Your dedication is inspiring!' : phrases.R
korean : 'Your dedication is inspiring!' : phrases.R
turkish : 'Your dedication is inspiring!' : phrases.R
chinese_simplified : 'All that practice is paying off!' : phrases.R
french : 'All that practice is paying off!' : phrases.R
german : 'All that practice is paying off!' : phrases.R
korean : 'All that practice is paying off!' : phrases.R
turkish : 'All that practice is paying off!' : phrases.R
chinese_simplified : 'Excellent work!' : phrases.R
french : 'Excellent work!' : phrases.R
german : 'Excellent work!' : phrases.R
korean : 'Excellent work!' : phrases.R
turkish : 'Excellent work!' : phrases.R
chinese_simplified : 'That's the answer I was looking for.' : phrases.R
french : 'That's the answer I was looking for.' : phrases.R
german : 'That's the answer I was looking for.' : phrases.R
korean : 'That's the answer I was looking for.' : phrases.R
turkish : 'That's the answer I was looking for.' : phrases.R
chinese_simplified : 'One more time. You can do it!' : phrases.R
french : 'One more time. You can do it!' : phrases.R
german : 'One more time. You can do it!' : phrases.R
korean : 'One more time. You can do it!' : phrases.R
turkish : 'One more time. You can do it!' : phrases.R
chinese_simplified : 'Not quite, but you're learning! Try again.' : phrases.R
french : 'Not quite, but you're learning! Try again.' : phrases.R
german : 'Not quite, but you're learning! Try again.' : phrases.R
korean : 'Not quite, but you're learning! Try again.' : phrases.R
turkish : 'Not quite, but you're learning! Try again.' : phrases.R
chinese_simplified : 'Try again. Getting it right on the first try is boring anyway!' : phrases.R
french : 'Try again. Getting it right on the first try is boring anyway!' : phrases.R
german : 'Try again. Getting it right on the first try is boring anyway!' : phrases.R
korean : 'Try again. Getting it right on the first try is boring anyway!' : phrases.R
turkish : 'Try again. Getting it right on the first try is boring anyway!' : phrases.R
```

**Comment by dhduncan** [comment]
I made a few changes, and @ismaeIfm did the rest. Sorry for the un-cordination hermano

**Comment by seankross** [comment]
Thanks everyone for the updates!

**Comment by ismaeIfm** [comment]
Hi everyone, testing swirl in spanish I noticed that some lines that were translated here, doesn't showed their respective translation in swirl.

![selection_002](https://cloud.githubusercontent.com/assets/7130927/13821565/c8ef4f90-eb67-11e5-8018-cf9425b58e0e.png)

![selection_003](https://cloud.githubusercontent.com/assets/7130927/13821573/d0901626-eb67-11e5-87c7-46c3f86c5b59.png)

**Comment by seankross** [comment]
@ismaeIfm great catch, I'll look into this.

**Comment by ismaeIfm** [comment]
Also I noticed that in Windows the spanish special characters are not correctly displayed in the menu messages of swirl, even though the text with special characters from the .yaml files is correctly displayed (lessons). I've also noticed that swirl adds line breaks between text.

Here you can see a comparison between swirl in Linux and swirl in Windows:
![12499551_10154712041948289_1398937307_o](https://cloud.githubusercontent.com/assets/7130927/13824131/60434c52-eb72-11e5-95f2-5c80c30fe10a.jpg)

Here is my output of Sys.getlocale() in Windows 10 in Spanish:

[1] "LC_COLLATE=Spanish_Mexico.1252;LC_CTYPE=Spanish_Mexico.1252;LC_MONETARY=Spanish_Mexico.1252;LC_NUMERIC=C;LC_TIME=Spanish_Mexico.1252"

This problem is also present in Mac OS but with a proper config of locale is corrected, ie running 
`Sys.setlocale("LC_ALL", "en_US.UTF-8")
` before launching swirl.

**Comment by seankross** [comment]
Wow, thanks for catching this. I have an idea for a fix.

**Comment by seankross** [comment]
Try to install the new development version and let me know if the special characters look correct on windows. You'll have uninstall swirl, reinstall swirl with `devtools::install_github("swirldev/swirl", ref = dev)`, restart RStudio, call `library(swirl)`, do `select_language()`, and then `swirl()`.

**Comment by ismaeIfm** [comment]
@seankross thanks to you

**Comment by ismaeIfm** [comment]
Yeah @seankross that solve the special characters issue, but the line breaks keep showing:
![12422270_10154712253708289_51900379_o](https://cloud.githubusercontent.com/assets/7130927/13825860/404ebec4-eb7a-11e5-8f48-02986c466474.jpg)

Now I noticed two more things:
1) The options when you run uninstall_all_courses() are not translated:
![12528467_10154712253718289_808197614_o](https://cloud.githubusercontent.com/assets/7130927/13825964/ba747766-eb7a-11e5-96ae-1b1ad7b38787.jpg)
*Note: I don't know if "Selection" needs to be translated.

2) The names of the lessons don't show the special characters:
What it looks like in Windows:
![12722374_10154712253713289_2103121526_o](https://cloud.githubusercontent.com/assets/7130927/13826070/4809a29a-eb7b-11e5-81ce-365dc987775d.jpg)

And as it should be:
![selection_004](https://cloud.githubusercontent.com/assets/7130927/13826128/8719eb3e-eb7b-11e5-8e8b-9ce519811c75.png)

I guess this problem is also present in the names of the courses.

I had commented you that I was having some issues with the MANIFEST file when special characters where present. If I created the MANIFEST file (with UTF-8 encoding) in Windows/Linux, when I tried to install the course in Mac OS I had some issues, and vice versa. But I write you a mail more detailed, maybe you want to check at that.

**Comment by seankross** [comment]
All great catches. What do you get as a result of `getOption("width")`? I think there aren't newlines inserted, there's just something going on with `swirl_out()` which is in `utilities.R`. So todo for me:
- [x] Make sure all `"Yes"`s and `"No"`s are translated.
- [x] Make sure course and lesson names are encoded correctly.

**Comment by ismaeIfm** [comment]
97

**Comment by seankross** [comment]
Hmm, I'll check this out on my windows machine at home but it has to do with how a user has that option set.

**Comment by ismaeIfm** [comment]
Curious, cause I've seen these issue in many students using Windows and none in linux or mac.

**Comment by seankross** [comment]
Does it happen in English?

**Comment by ismaeIfm** [comment]
Yes and even with cran version of swirl:
![break](https://cloud.githubusercontent.com/assets/7130927/13828632/1cf2262e-eb88-11e5-995c-050fc93a5a9d.jpg)

**Comment by dhduncan** [comment]
I can't get the test version up and running on my mac. I uninstalled swirl, and reinstalled it as prescribed, but select_language() was not recognised as a function.

It worked with my linux machine however. I got no line breaks.
![screenshot 2016-03-16 16 23 48](https://cloud.githubusercontent.com/assets/5265962/13829217/d10a7dfe-eb93-11e5-950e-f977b7360610.png)

**Comment by seankross** [comment]
A brand new version of R recently came out, you may need to install it.

**Comment by dhduncan** [comment]
@seankross ok, downloading it now

**Comment by dhduncan** [comment]
OK, it looks good on both my machines, great work people!

![screenshot 2016-03-16 16 57 56](https://cloud.githubusercontent.com/assets/5265962/13830093/94b4ec36-eb98-11e5-8408-76a31b328986.png)

**Comment by dhduncan** [comment]
I'm still getting messages generated in response to dependson.txt such as

> Attempting to load lesson dependencies...  

and 

> Package ‘ggplot2’ loaded correctly!  

in English, is that to be expected?

**Comment by seankross** [comment]
@dhduncan that is not to be expected, I will fix it. Thank you!

**Comment by seankross** [comment]
Encoding issues should now be fixed on the dev branch. You can test it with `swirl::install_course_github("seankross", "New_Cou-rse")`.

**Comment by seankross** [comment]
@swirldev/translators I really mean it this time: I will be submitting swirl to CRAN on Friday (March 18th). Again a very serious that you to all of you for volunteering your time.

**Comment by ismaeIfm** [comment]
@seankross To me the encoding issues in Windows were not corrected, now they are worse:
![enco](https://cloud.githubusercontent.com/assets/7130927/13833688/b71d733c-ebad-11e5-9856-6ff1f85869ff.jpg)
It also happens with my course, now I get NA in the names that use special characters and an Error when selecting that lesson. And to the course name seems to be added the name of the user and an id.

Should not be corrected this line in Mac OS?
![mac](https://cloud.githubusercontent.com/assets/7130927/13833779/7fb551ac-ebae-11e5-823b-1f4bb2360036.jpg)
Also the yes and no don't show up translated.

**Comment by ismaeIfm** [comment]
And now in linux I got the following warning:
![screenshot from 2016-03-16 20 14 30](https://cloud.githubusercontent.com/assets/7130927/13834346/e365b6e2-ebb3-11e5-9c55-a89a37bf4bb6.png)

**Comment by seankross** [comment]
Make sure you:
1. Uninstall swirl
2. Install swirl
3. Restart RStudio
4. swirl()

And let me know if this persists.

**Comment by ismaeIfm** [comment]
@seankross to solve which of three issues?

**Comment by ismaeIfm** [comment]
The linux warning and the missing lines in Mac OS are solved, sorry. But the problem with the name lessons (NA) in Windows persists.

**Comment by seankross** [comment]
Does the NA still persist even with the very newest version? `devtools::install_github("swirldev/swirl", ref = dev)` (Then restart everything)

**Comment by ismaeIfm** [comment]
Yes, this problem has appeared since you update swirl to solved the encoding. Before this updated only the characters were not correctly displayed in Windows. The branch "ismael" of swirl displays the names as the "dev" branch did it (Not correctly but not displayed NA).

**Comment by nFrechen** [comment]
I think I used ":" in one of my translated sentences and this might break the translation, too. At least my syntax highlighter suggests that.

**Comment by nFrechen** [comment]
This sentence looks like a continuation from another. How does it start?
"right now. Are you sure you have an internet connection?":

**Comment by nFrechen** [comment]
In english.yaml there is still this duplicate entry I think:

```
You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If you are already at the prompt, type bye() to exit and save your progress. When you exit properly, you'll see a short message letting
```

This sentence ends with:

```
you know you've done so.
```

in line 585 and

```
know you've done so. 
```

in line 340.

But maybe having this twice is intended.

**Comment by seankross** [comment]
Hi @nFrechen, I'll check all of that out and make it's working/makes sense. I just figured out the situation with the NAs at lesson selection. Copy the following into a file called test.txt

```
à la carte
Curaçao
coup d'état
crêpe
daïs
filmjölk
Gemütlichkeit
jäger
jalapeño
汉字
العربية
देवनागरी
Кирилица
Ελληνικό
אלפבית
한국어
日本語

```

Now compare the results of this code:

``` r
readLines("test.txt")
readLines("test.txt", encoding = "UTF-8")
x <- readLines("test.txt", encoding = "UTF-8")
writeLines(x, "test2.txt")
writeLines(x, "test2.txt", useBytes = TRUE)
```

Looks like I need to make changes to swirlify as well. swirldev/swirlify#18

**Comment by ismaeIfm** [comment]
@seankross This is what I get:
![enco](https://cloud.githubusercontent.com/assets/7130927/13861065/f55050a4-ec50-11e5-953c-fc57d71a09f2.png)
Do you think these is related to the issue I told you about creating MANIFEST with add_manifest() across Linux/Windows and Mac OS?

**Comment by seankross** [comment]
It is for sure. The changes have to be made in swirlify.

**Comment by seankross** [comment]
Something worth exploring: are the manifest files valid yaml?

**Comment by ismaeIfm** [comment]
@seankross It is a rhetorical question?

**Comment by seankross** [comment]
It's a note to self. But if you want to run yaml::yaml.load_file() on a
manifest file go for it. I'm afk for the rest of the day but I'm always
reading email on my phone.

**Comment by ismaeIfm** [comment]
I noticed something curious by default Windows in spanish has saved the file "test.text" in ASCII, to get the right encoding I have to tell explicitly to Windows that I want it in UTF-8:
![message](https://cloud.githubusercontent.com/assets/7130927/13861561/92491984-ec53-11e5-97cf-116a3a77e2fc.png)
![utf](https://cloud.githubusercontent.com/assets/7130927/13861565/9517aa5e-ec53-11e5-9326-92245328ae93.png)
I found it curious because it is Windows in Spanish.

**Comment by dhduncan** [comment]
@ismaeIfm  I agree. I find it so odd that PCs "born" into Windows in a spanish speaking environment for some reason fail to apply sensible defaults to these files.

**Comment by seankross** [comment]
I just submitted swirl 2.4.0. I tried to handle the manifest issues as best as possible, unfortunately I think the general guidance will have to be that course authors should stick to ascii in the manifest, however a much wider range of alphabets are supported within the lessons. The general rule is, if your manifest introduces NAs, the manifest gets thrown out. I'm going to close this issue since the next alert to translators will be for the next release of swirl. I expect swirl to follow a very regular release schedule from now on with a patch or release every one or two months.
